import { defineTemplate } from '../define.mjs';

export default defineTemplate({
  id: 'competitor-watcher',
  name: 'Competitor Watcher',
  title: 'Competitor Watcher',
  subtitle: 'A living doc shape for tracking competitors across monitoring periods — strategic posture, discrete moves, indicators, and a market-position map. Each check-in lands as a delta, so the picture accumulates rather than restarts.',
  scope: 'One market, one set of named competitors, tracked over time. Strategic posture revealed through behavior. Discrete moves logged with intent and outcome. Indicators refreshed on a cadence. A two-axis map showing where each competitor sits and how they moved.',
  objective: "Track the evolution of <market>'s competitive landscape so any reader at any period check-in sees current strategic posture per competitor, the moves they made this period, live indicator values, predictions still pending, and where each player sits on the map vs. where they used to sit.",
  successCondition: "A reader opening the doc at the end of any monitoring period knows (1) each tracked competitor's current posture and how it shifted, (2) the discrete moves each one made in the period with intent and outcome, (3) the latest indicator values with dated sources, and (4) which competitors moved on the position map and in which direction.",
  templatePath: 'docs/living-doc-template-competitor-watcher.json',
  objectiveRole: 'Track competitive posture over time by separating competitors, moves, predictions, indicators, positions, sources, and period notes.',
  sections: [
    {
      id: 'competitors',
      title: 'Tracked competitors',
      convergenceType: 'competitor-stance-track',
      role: 'Track named competitors and their current strategic posture.',
      rationale: 'The named organizations whose strategic posture we watch over time. One card per competitor, with current bet and evolution surfaced as first-class fields.',
    },
    {
      id: 'moves',
      title: 'Strategic moves this period',
      convergenceType: 'strategic-move-log',
      role: 'Log discrete competitor actions with intent and observed outcome.',
      rationale: 'Discrete actions taken by tracked competitors with observable consequences. Moves are events; citations are what you read about them. Keep separate.',
    },
    {
      id: 'predictions',
      title: 'What comes next',
      convergenceType: 'proof-ladder',
      role: 'Track predictions about competitor moves or market outcomes.',
      rationale: 'Predictions about future competitor moves or market outcomes. Each rung resolves as evidence accumulates.',
    },
    {
      id: 'indicators',
      title: 'Indicator dashboard',
      convergenceType: 'indicator-trace',
      role: 'Track numeric or categorical indicators that show competitive movement.',
      rationale: 'Numeric indicators tracked across periods. Carry the value as text; carry direction as a categorical trend.',
    },
    {
      id: 'positions',
      title: 'Market position map',
      convergenceType: 'position-cluster-map',
      role: 'Map competitor position and movement between periods.',
      rationale: 'Two-axis placement of tracked competitors. Movement between periods is the primary signal; prior positions are preserved per card.',
    },
    {
      id: 'sources',
      title: 'Sources this period',
      convergenceType: 'citation-feed',
      role: 'Preserve the sources consumed during the current competitive monitoring period.',
      rationale: 'Articles, earnings transcripts, analyst reports, interviews you consumed this period. Sources are what you READ; moves are what HAPPENED. Keep them in their own sections.',
    },
    {
      id: 'period-notes',
      title: 'Period notes',
      convergenceType: 'decision-record',
      role: 'Summarize what moved, resolved, and matters for the next period.',
      rationale: 'One card per monitoring period summarising what moved, what resolved, and what matters for the next period.',
    },
  ],
  relationships: [
    {
      id: 'sources-inform-competitor-posture',
      from: 'citation-feed',
      to: 'competitor-stance-track',
      relation: 'informs',
      rationale: 'Competitor posture should be inferred from dated sources and observed behavior.',
    },
    {
      id: 'competitors-make-moves',
      from: 'competitor-stance-track',
      to: 'strategic-move-log',
      relation: 'makes',
      rationale: 'Strategic moves must identify which tracked competitor made the move.',
      evidence: {
        kind: 'shared-field-value',
        sourceFields: ['id', 'name'],
        targetFields: ['byCompany', 'competitorIds', 'companyIds'],
        description: 'A move should identify the competitor or company that made it.',
      },
      repairOperationIds: ['add-strategic-move'],
    },
    {
      id: 'moves-drive-indicators',
      from: 'strategic-move-log',
      to: 'indicator-trace',
      relation: 'drives',
      rationale: 'Discrete moves should connect to indicator changes when their effect is observable.',
    },
    {
      id: 'competitors-positioned-on-map',
      from: 'competitor-stance-track',
      to: 'position-cluster-map',
      relation: 'positioned-on',
      rationale: 'Tracked competitors should appear on the market position map so movement is visible.',
    },
    {
      id: 'indicators-resolve-predictions',
      from: 'indicator-trace',
      to: 'proof-ladder',
      relation: 'resolves',
      rationale: 'Indicator movement and strategic moves resolve or weaken predictions.',
    },
    {
      id: 'period-notes-summarize-competitive-landscape',
      from: 'decision-record',
      to: 'competitor-stance-track',
      relation: 'summarizes',
      rationale: 'Period notes should summarize posture shifts, moves, indicators, predictions, and map movement.',
    },
  ],
  stageSignals: [
    {
      id: 'seeding-missing-competitors',
      stage: 'Seeding',
      severity: 'high',
      when: 'competitor-stance-track has no tracked competitors',
      condition: { kind: 'section-empty', type: 'competitor-stance-track' },
      question: 'Which competitors define this market watch?',
    },
    {
      id: 'composition-competitors-without-sources',
      stage: 'Composition',
      severity: 'medium',
      when: 'competitors exist but citation-feed has no sources',
      condition: {
        kind: 'source-populated-target-empty',
        sourceType: 'competitor-stance-track',
        targetType: 'citation-feed',
      },
      question: 'Which source supports the current competitor posture?',
      relatedRelationships: ['sources-inform-competitor-posture'],
    },
    {
      id: 'coherence-competitor-without-moves',
      stage: 'Coherence',
      severity: 'high',
      when: 'competitors exist but strategic-move-log lacks corresponding moves',
      condition: { kind: 'related-relationship-gap' },
      question: 'Which tracked competitor made a discrete strategic move this period?',
      relatedRelationships: ['competitors-make-moves'],
    },
    {
      id: 'operation-competitors-without-position-map',
      stage: 'Operation',
      severity: 'medium',
      when: 'competitors exist but position-cluster-map is empty',
      condition: {
        kind: 'source-populated-target-empty',
        sourceType: 'competitor-stance-track',
        targetType: 'position-cluster-map',
      },
      question: 'Where does each competitor sit on the market position map this period?',
      relatedRelationships: ['competitors-positioned-on-map'],
    },
    {
      id: 'judgment-competitor-period-ready',
      stage: 'Judgment',
      severity: 'high',
      when: 'competitors, moves, predictions, indicators, positions, sources, and notes are populated',
      condition: {
        kind: 'all-populated-no-high-gaps',
        types: ['competitor-stance-track', 'strategic-move-log', 'proof-ladder', 'indicator-trace', 'position-cluster-map', 'citation-feed', 'decision-record'],
      },
      question: 'Can a reader see each competitor posture, moves, indicators, and map movement for this period?',
      relatedRelationships: ['competitors-make-moves', 'competitors-positioned-on-map', 'indicators-resolve-predictions'],
    },
  ],
  validOperations: [
    {
      id: 'add-competitor',
      label: 'Add competitor',
      stages: ['Seeding', 'Composition'],
      description: 'Add a tracked competitor with posture, current bet, and evolution.',
      patchKind: 'card-create',
    },
    {
      id: 'add-strategic-move',
      label: 'Add strategic move',
      stages: ['Composition', 'Coherence'],
      description: 'Add a dated strategic move by a tracked competitor.',
      patchKind: 'card-create',
    },
    {
      id: 'record-competitor-indicator',
      label: 'Record competitor indicator',
      stages: ['Operation', 'Refresh'],
      description: 'Add or update an indicator value connected to competitive movement.',
      patchKind: 'card-create',
    },
    {
      id: 'update-market-position',
      label: 'Update market position',
      stages: ['Operation', 'Refresh'],
      description: 'Add or update a competitor position and movement on the map.',
      patchKind: 'card-create',
    },
    {
      id: 'write-competitor-period-note',
      label: 'Write competitor period note',
      stages: ['Judgment'],
      description: 'Record what moved, resolved, and matters for next period.',
      patchKind: 'card-create',
    },
  ],
});
