import { defineTemplate } from '../define.mjs';

export default defineTemplate({
  id: 'design-system',
  name: 'Design a System',
  title: 'Design a System — your taste, one client at a time',
  subtitle: 'A small starting shape for designers building a client design system while keeping their own taste-signature visible and evidenced across prior work.',
  scope: "The designer's recurring taste across prior systems, plus the system being built for the current client engagement — alignment to the brief, derivation moves from prior systems, and the current state of the new system as pointers.",
  objective: 'Make the design system you are building visible end-to-end: where each primitive lives, why it answers the brief, what it inherits from your prior work, and what about it is uniquely you.',
  successCondition: 'Every primitive in the surface has a pointer (not a duplicated value). Every alignment card has both a constraint and a response. Every derivation card has a prior-system pointer and a one-or-two-sentence rationale. Every recurring taste card has at least two prior-system pointers as evidence.',
  templatePath: 'docs/living-doc-template-design-system.json',
  objectiveRole: 'Make design-system work legible by connecting taste evidence, brief alignment, derivation moves, and surface pointers.',
  sections: [
    {
      id: 'status-snapshot',
      title: 'Status Snapshot',
      convergenceType: 'status-snapshot',
      role: 'Summarize design-system readiness without carrying the design evidence.',
      rationale: 'This section keeps client-system status visible while taste, alignment, derivation, and surface pointers stay distinct.',
    },
    {
      id: 'taste-signature',
      title: 'Taste Signature',
      convergenceType: 'taste-signature',
      role: 'Expose recurring designer traits evidenced by prior systems.',
      rationale: 'Taste has to be evidenced through prior systems so it becomes an inspectable design input rather than a vague personal claim.',
    },
    {
      id: 'brief-alignment',
      title: 'Brief to System Alignment',
      convergenceType: 'brief-to-system-alignment',
      role: 'Translate client constraints into concrete system responses.',
      rationale: 'Each alignment card pairs a brief constraint with a design response so the client system can be judged against the actual engagement.',
    },
    {
      id: 'derivation',
      title: 'Design System Derivation',
      convergenceType: 'design-system-derivation',
      role: 'Track what the new system inherits or transforms from prior work.',
      rationale: 'Derivation cards keep inherited taste moves explicit and grounded in prior-system references.',
    },
    {
      id: 'surface',
      title: 'Design System Surface',
      convergenceType: 'design-system-surface',
      role: 'Expose the current design system as pointers to tokens, components, and motifs.',
      rationale: 'The system surface should point to primitives where they live instead of duplicating token or component values inside the doc.',
    },
  ],
  relationships: [
    {
      id: 'status-summarizes-system-surface',
      from: 'status-snapshot',
      to: 'design-system-surface',
      relation: 'summarizes',
      rationale: 'Design-system status should summarize the actual primitive surface being built.',
    },
    {
      id: 'taste-feeds-derivation',
      from: 'taste-signature',
      to: 'design-system-derivation',
      relation: 'feeds',
      rationale: 'Derivation moves should be grounded in evidenced taste from prior systems.',
      evidence: {
        kind: 'shared-field-value',
        sourceFields: ['priorSystemRefs', 'tokenRefs', 'componentRefs', 'motifRefs'],
        targetFields: ['priorSystemRefs', 'tokenRefs', 'componentRefs', 'motifRefs'],
        description: 'A derivation card should identify prior systems, tokens, components, or motifs that evidence the taste move.',
      },
      repairOperationIds: ['add-derivation-card'],
    },
    {
      id: 'brief-feeds-alignment',
      from: 'brief-to-system-alignment',
      to: 'design-system-surface',
      relation: 'constrains',
      rationale: 'System primitives should be traceable to brief constraints and responses.',
    },
    {
      id: 'derivation-produces-surface',
      from: 'design-system-derivation',
      to: 'design-system-surface',
      relation: 'produces',
      rationale: 'Derivation moves become useful when they point at actual tokens, components, or motifs in the system surface.',
    },
  ],
  stageSignals: [
    {
      id: 'seeding-missing-system-surface',
      stage: 'Seeding',
      severity: 'high',
      when: 'design-system-surface has no primitive pointers',
      condition: { kind: 'section-empty', type: 'design-system-surface' },
      question: 'What first token, component, or motif pointer makes this client system tangible?',
    },
    {
      id: 'coherence-taste-not-derived',
      stage: 'Coherence',
      severity: 'high',
      when: 'taste-signature exists but design-system-derivation has no corresponding derivation moves',
      condition: { kind: 'related-relationship-gap' },
      question: 'Which taste trait still needs a derivation move into the client system?',
      relatedRelationships: ['taste-feeds-derivation'],
    },
    {
      id: 'operation-surface-without-brief-alignment',
      stage: 'Operation',
      severity: 'medium',
      when: 'system surface exists but brief-to-system-alignment has no cards',
      condition: {
        kind: 'source-populated-target-empty',
        sourceType: 'design-system-surface',
        targetType: 'brief-to-system-alignment',
      },
      question: 'Which brief constraint does the current primitive answer?',
      relatedRelationships: ['brief-feeds-alignment'],
    },
    {
      id: 'judgment-design-system-ready',
      stage: 'Judgment',
      severity: 'high',
      when: 'taste, alignment, derivation, and surface are all populated and linked',
      condition: {
        kind: 'all-populated-no-high-gaps',
        types: ['taste-signature', 'brief-to-system-alignment', 'design-system-derivation', 'design-system-surface'],
      },
      question: 'Can the system be defended as client-aligned, pointer-based, and distinctively grounded in prior taste?',
      relatedRelationships: ['taste-feeds-derivation', 'brief-feeds-alignment', 'derivation-produces-surface'],
    },
  ],
  validOperations: [
    {
      id: 'add-system-surface-primitive',
      label: 'Add system surface primitive',
      stages: ['Seeding', 'Composition'],
      description: 'Add a token, component, or motif pointer that belongs to the client system.',
      patchKind: 'card-create',
    },
    {
      id: 'add-taste-trait',
      label: 'Add taste trait',
      stages: ['Seeding', 'Composition'],
      description: 'Add a taste-signature trait evidenced by prior systems.',
      patchKind: 'card-create',
    },
    {
      id: 'add-brief-alignment',
      label: 'Add brief alignment',
      stages: ['Composition', 'Coherence'],
      description: 'Add a constraint/response card that ties the system to the client brief.',
      patchKind: 'card-create',
    },
    {
      id: 'add-derivation-card',
      label: 'Add derivation card',
      stages: ['Coherence', 'Operation'],
      description: 'Add a derivation move from prior system evidence to a current primitive.',
      patchKind: 'card-create',
    },
  ],
});
