import { defineTemplate } from '../define.mjs';

export default defineTemplate({
  id: 'monitoring-tracker',
  name: 'Monitoring Tracker',
  title: 'Monitoring Tracker',
  subtitle: "A living doc shape for topics that don't end — track named voices, empirical predictions, and numeric indicators every check-in, with each period visible as a delta.",
  scope: 'One topic or domain, tracked over time. Named experts whose stances evolve; predictions whose resolution accumulates evidence; indicators whose values print on a cadence; a consensus map where movement between periods is the signal.',
  objective: 'Track the evolution of <topic> as evidence accumulates and named positions shift, so any reader at any period check-in sees current stance, live prediction resolutions, latest indicator values, and what moved since the prior period — without re-reading the underlying sources.',
  successCondition: "A reader opening the doc at the end of any monitoring period knows (1) each expert's current stance and how it shifted, (2) which predictions moved toward resolution, (3) the latest indicator values with dated sources, and (4) where the consensus has tightened or widened on the map.",
  templatePath: 'docs/living-doc-template-monitoring-tracker.json',
  objectiveRole: 'Track an evolving topic across periods by separating voices, predictions, indicators, map movement, sources, and period notes.',
  sections: [
    {
      id: 'experts',
      title: 'Tracked voices',
      convergenceType: 'expert-stance-track',
      role: 'Track named voices and how their stances evolve over monitoring periods.',
      rationale: 'The named voices whose public-intellectual stance evolves over time. One card per voice.',
    },
    {
      id: 'predictions',
      title: 'Empirical predictions',
      convergenceType: 'proof-ladder',
      role: 'Track what-to-watch claims as evidence accumulates.',
      rationale: "The 'what to watch' claims rendered as a proof ladder. Each rung resolves as evidence accumulates across periods.",
    },
    {
      id: 'indicators',
      title: 'Indicator dashboard',
      convergenceType: 'indicator-trace',
      role: 'Track numeric indicators and their direction across periods.',
      rationale: 'Numeric indicators tracked across periods. Latest value is text; trend is categorical (rising/stable/falling/resolved).',
    },
    {
      id: 'divergence',
      title: 'Consensus & divergence map',
      convergenceType: 'position-cluster-map',
      role: 'Map current and prior positions so movement between periods is visible.',
      rationale: 'Two-axis placement of tracked voices. Movement between monitoring periods is the primary signal. Prior-period position is preserved on each card.',
    },
    {
      id: 'sources',
      title: 'Sources this period',
      convergenceType: 'citation-feed',
      role: 'Preserve the dated sources consumed during the current monitoring period.',
      rationale: 'Period-grouped citation feed. Each source added in the current period lives here; retroactive additions to prior periods are allowed but should be flagged in notes.',
    },
    {
      id: 'period-notes',
      title: 'Period notes',
      convergenceType: 'decision-record',
      role: 'Summarize what shifted, resolved, and matters for the next period.',
      rationale: 'One card per monitoring period summarising what shifted, what resolved, and what matters for next.',
    },
  ],
  relationships: [
    {
      id: 'sources-inform-expert-stances',
      from: 'citation-feed',
      to: 'expert-stance-track',
      relation: 'informs',
      rationale: 'Expert stance updates should be grounded in sources read during the monitoring period.',
    },
    {
      id: 'sources-inform-indicators',
      from: 'citation-feed',
      to: 'indicator-trace',
      relation: 'informs',
      rationale: 'Indicator values need dated source backing so period movement can be audited.',
    },
    {
      id: 'experts-positioned-on-map',
      from: 'expert-stance-track',
      to: 'position-cluster-map',
      relation: 'positioned-on',
      rationale: 'The consensus map should place tracked voices and preserve their movement between periods.',
    },
    {
      id: 'indicators-resolve-predictions',
      from: 'indicator-trace',
      to: 'proof-ladder',
      relation: 'resolves',
      rationale: 'Predictions move toward resolution when indicators change or new values arrive.',
    },
    {
      id: 'period-notes-summarize-tracker',
      from: 'decision-record',
      to: 'expert-stance-track',
      relation: 'summarizes',
      rationale: 'Period notes should summarize stance shifts, prediction movement, indicator changes, and map movement.',
    },
  ],
  stageSignals: [
    {
      id: 'seeding-missing-voices',
      stage: 'Seeding',
      severity: 'high',
      when: 'expert-stance-track has no tracked voices',
      condition: { kind: 'section-empty', type: 'expert-stance-track' },
      question: 'Which named voices define this monitoring topic?',
    },
    {
      id: 'composition-voices-without-sources',
      stage: 'Composition',
      severity: 'medium',
      when: 'expert stances exist but citation-feed has no sources',
      condition: {
        kind: 'source-populated-target-empty',
        sourceType: 'expert-stance-track',
        targetType: 'citation-feed',
      },
      question: 'Which dated source supports the current stance update?',
      relatedRelationships: ['sources-inform-expert-stances'],
    },
    {
      id: 'coherence-stances-without-map',
      stage: 'Coherence',
      severity: 'high',
      when: 'expert stances exist but position-cluster-map is empty',
      condition: {
        kind: 'source-populated-target-empty',
        sourceType: 'expert-stance-track',
        targetType: 'position-cluster-map',
      },
      question: 'Where do the tracked voices sit on the consensus map this period?',
      relatedRelationships: ['experts-positioned-on-map'],
    },
    {
      id: 'operation-indicators-without-prediction-movement',
      stage: 'Operation',
      severity: 'medium',
      when: 'indicators exist but proof-ladder has no prediction rungs',
      condition: {
        kind: 'source-populated-target-empty',
        sourceType: 'indicator-trace',
        targetType: 'proof-ladder',
      },
      question: 'Which prediction did the indicator value move toward resolution?',
      relatedRelationships: ['indicators-resolve-predictions'],
    },
    {
      id: 'judgment-monitoring-period-ready',
      stage: 'Judgment',
      severity: 'high',
      when: 'voices, predictions, indicators, map, sources, and period notes are populated',
      condition: {
        kind: 'all-populated-no-high-gaps',
        types: ['expert-stance-track', 'proof-ladder', 'indicator-trace', 'position-cluster-map', 'citation-feed', 'decision-record'],
      },
      question: 'Can a reader understand what shifted this period without rereading the sources?',
      relatedRelationships: ['sources-inform-expert-stances', 'experts-positioned-on-map', 'indicators-resolve-predictions'],
    },
  ],
  validOperations: [
    {
      id: 'add-tracked-voice',
      label: 'Add tracked voice',
      stages: ['Seeding', 'Composition'],
      description: 'Add a named expert or voice with current stance and evolution.',
      patchKind: 'card-create',
    },
    {
      id: 'add-period-source',
      label: 'Add period source',
      stages: ['Composition', 'Refresh'],
      description: 'Add a dated source consumed during the current monitoring period.',
      patchKind: 'card-create',
    },
    {
      id: 'update-position-map',
      label: 'Update position map',
      stages: ['Coherence', 'Refresh'],
      description: 'Add or update the consensus/divergence map position for a tracked voice.',
      patchKind: 'card-create',
    },
    {
      id: 'record-indicator-value',
      label: 'Record indicator value',
      stages: ['Operation', 'Refresh'],
      description: 'Add or update a dated numeric indicator value and trend.',
      patchKind: 'card-create',
    },
    {
      id: 'write-period-note',
      label: 'Write period note',
      stages: ['Judgment'],
      description: 'Record what shifted, resolved, and matters for the next monitoring period.',
      patchKind: 'card-create',
    },
  ],
});
