import { defineTemplate } from '../define.mjs';

export default defineTemplate({
  id: 'operations-support',
  name: 'Operations and Support',
  title: 'Operations and Support',
  subtitle: 'A compact starting shape for mediated workflows, support surfaces, and the tools that keep them operational.',
  scope: 'A support or operations domain where requests, operational surfaces, enablers, and tooling need to be reasoned about together.',
  objective: 'Make an operations or support domain legible across request flow, operational surfaces, enabling assets, and the tools used to support the work.',
  successCondition: 'A reader can see how requests enter the system, which support paths exist, what enablers are available, and which tools the operators rely on.',
  templatePath: 'docs/living-doc-template-operations-support.json',
  objectiveRole: 'Make an operations or support domain legible across request flow, operating surfaces, enabling assets, and tooling.',
  sections: [
    {
      id: 'status-snapshot',
      title: 'Status Snapshot',
      convergenceType: 'status-snapshot',
      role: 'Summarize operational readiness and current support pressure without carrying detailed request or tooling evidence.',
      rationale: 'This section keeps operational readiness visible without turning requests, support lanes, enablers, or tooling into dashboard prose.',
    },
    {
      id: 'operations',
      title: 'Mediated Operation',
      convergenceType: 'operation',
      role: 'Describe the mediated request-to-execution flow that operators need to run.',
      rationale: 'The core operation has to name how work enters, moves, and gets mediated before support surfaces can be evaluated.',
    },
    {
      id: 'support-surface',
      title: 'Operating Surface',
      convergenceType: 'operating-surface',
      role: 'Expose the bounded support lanes or operational paths that request flow routes into.',
      rationale: 'Support lanes are separated from request flow so each bounded operating path can be assessed and improved.',
    },
    {
      id: 'enablers',
      title: 'Enabler Catalog',
      convergenceType: 'enabler-catalog',
      role: 'Catalog compact support assets that improve operator speed, reliability, or coverage.',
      rationale: 'Operators need visible snippets, assets, fixtures, or runbooks that make the operating surfaces easier and safer to run.',
    },
    {
      id: 'tooling',
      title: 'Tooling Surface',
      convergenceType: 'tooling-surface',
      role: 'Expose the scripts, workflows, and local tools used to operate or evolve the support domain.',
      rationale: 'Operational claims need concrete tool paths so support work can be rerun, inspected, or extended.',
    },
  ],
  relationships: [
    {
      id: 'status-summarizes-operation',
      from: 'status-snapshot',
      to: 'operation',
      relation: 'summarizes',
      rationale: 'Operational status should summarize real support flow rather than stand apart as a dashboard label.',
    },
    {
      id: 'operation-routes-surface',
      from: 'operation',
      to: 'operating-surface',
      relation: 'routes-to',
      rationale: 'Mediated operations should name the concrete support lanes or operating surfaces they route requests into.',
      evidence: {
        kind: 'shared-field-value',
        sourceFields: ['id', 'workflowPaths', 'requestInputs'],
        targetFields: ['operationIds', 'workflowPaths', 'requestInputs'],
        description: 'An operating surface should identify the operation, workflow path, or request input it supports.',
      },
      repairOperationIds: ['add-operating-surface-card'],
    },
    {
      id: 'surface-needs-enablers',
      from: 'operating-surface',
      to: 'enabler-catalog',
      relation: 'needs',
      rationale: 'Support lanes stay operational only when their enabling snippets, fixtures, runbooks, or assets are visible.',
    },
    {
      id: 'tooling-supports-operation',
      from: 'tooling-surface',
      to: 'operation',
      relation: 'supports',
      rationale: 'Operational request flow needs a tool path so a future session can rerun, inspect, or extend the support process.',
    },
  ],
  stageSignals: [
    {
      id: 'seeding-missing-operation',
      stage: 'Seeding',
      severity: 'high',
      when: 'operation has no request-flow cards',
      condition: { kind: 'section-empty', type: 'operation' },
      question: 'What first real request flow, intake path, or mediated operation makes this support doc tangible?',
    },
    {
      id: 'coherence-operation-not-routed',
      stage: 'Coherence',
      severity: 'high',
      when: 'operation exists but operating-surface has no corresponding support lanes',
      condition: { kind: 'related-relationship-gap' },
      question: 'Which operation cards lack a concrete support lane or operating surface?',
      relatedRelationships: ['operation-routes-surface'],
    },
    {
      id: 'operation-surface-without-enablers',
      stage: 'Operation',
      severity: 'medium',
      when: 'operating-surface has lanes but enabler-catalog has no assets that support them',
      condition: {
        kind: 'source-populated-target-empty',
        sourceType: 'operating-surface',
        targetType: 'enabler-catalog',
      },
      question: 'Which enabler would make the current support lane faster, safer, or easier to operate?',
      relatedRelationships: ['surface-needs-enablers'],
    },
    {
      id: 'judgment-support-readiness',
      stage: 'Judgment',
      severity: 'high',
      when: 'operation, operating surface, enablers, and tooling are all populated and linked',
      condition: {
        kind: 'all-populated-no-high-gaps',
        types: ['operation', 'operating-surface', 'enabler-catalog', 'tooling-surface'],
      },
      question: 'Can the support domain be operated from this document, or are key request paths still implicit?',
      relatedRelationships: ['operation-routes-surface', 'surface-needs-enablers', 'tooling-supports-operation'],
    },
  ],
  validOperations: [
    {
      id: 'add-operation-card',
      label: 'Add operation card',
      stages: ['Seeding', 'Composition'],
      description: 'Add a request-flow or mediated-operation card that names how work enters and moves through the support domain.',
      patchKind: 'card-create',
    },
    {
      id: 'add-operating-surface-card',
      label: 'Add operating surface card',
      stages: ['Composition', 'Coherence'],
      description: 'Add a bounded support lane or operational surface that a request flow routes into.',
      patchKind: 'card-create',
    },
    {
      id: 'add-enabler-card',
      label: 'Add enabler card',
      stages: ['Coherence', 'Operation'],
      description: 'Add a support asset, runbook, fixture, or snippet that strengthens an operating surface.',
      patchKind: 'card-create',
    },
    {
      id: 'link-tooling-to-operation',
      label: 'Link tooling to operation',
      stages: ['Operation', 'Refresh'],
      description: 'Link the script, workflow, or local tool used to run or inspect the operation.',
      patchKind: 'card-update',
    },
    {
      id: 'lower-support-status',
      label: 'Lower support status',
      stages: ['Coherence', 'Refresh', 'Judgment'],
      description: 'Lower or qualify operational readiness when support lanes, enablers, or tooling do not support the claim.',
      patchKind: 'card-update',
    },
  ],
});
