#!/usr/bin/env node
/**
 * build-kit.mjs — produce a self-contained bundle folder from a profile JSON.
 *
 * Usage:
 *   node scripts/build-kit.mjs <profile.json> [out-dir]
 *
 * The bundle is a mini-repo with the same layout as this project, carrying
 * only the convergence types + starter templates listed in the profile.
 *
 * Layout:
 *   <out>/README.md
 *   <out>/docs/living-doc-compositor.html          (branded)
 *   <out>/docs/templates/<starter>.json
 *   <out>/scripts/render-living-doc.mjs
 *   <out>/scripts/living-doc-registry.json         (filtered)
 *   <out>/scripts/living-doc-i18n.json
 *   <out>/scripts/sync-compositor-embeds.mjs
 *   <out>/scripts/meta-fingerprint.mjs
 */

import { readFile, writeFile, mkdir, cp } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, '..');

export function filterRegistry(registry, includedConvergenceTypes) {
  const included = new Set(includedConvergenceTypes);
  const filteredConvergenceTypes = {};
  const requiredEntityTypes = new Set();
  const requiredStatusSets = new Set();

  for (const [id, entry] of Object.entries(registry.convergenceTypes)) {
    if (!included.has(id)) continue;
    filteredConvergenceTypes[id] = entry;
    for (const src of entry.sources ?? []) {
      if (src.entityType) requiredEntityTypes.add(src.entityType);
    }
    for (const sf of entry.statusFields ?? []) {
      if (sf.statusSet) requiredStatusSets.add(sf.statusSet);
    }
  }

  const filteredEntityTypes = {};
  for (const [id, entry] of Object.entries(registry.entityTypes ?? {})) {
    if (requiredEntityTypes.has(id)) filteredEntityTypes[id] = entry;
  }
  const filteredStatusSets = {};
  for (const [id, entry] of Object.entries(registry.statusSets ?? {})) {
    if (requiredStatusSets.has(id)) filteredStatusSets[id] = entry;
  }

  return {
    schemaVersion: registry.schemaVersion,
    entityTypes: filteredEntityTypes,
    statusSets: filteredStatusSets,
    convergenceTypes: filteredConvergenceTypes,
  };
}

export function brandCompositor(html, branding) {
  if (!branding) return html;
  const orgName = (branding.orgName || '').trim();
  const primary = (branding.primaryColor || '').trim();
  const injections = [];
  if (primary) {
    injections.push(`:root { --accent: ${primary} !important; }`);
  }
  if (!injections.length && !orgName) return html;
  const styleTag = injections.length
    ? `<style id="ldc-brand-overrides">${injections.join('\n')}</style>`
    : '';
  const scriptTag = orgName
    ? `<script>window.__LDC_BRAND__=${JSON.stringify({ orgName })};</script>`
    : '';
  return html.replace('</head>', `${styleTag}${scriptTag}</head>`);
}

function renderReadme(profile) {
  const name = profile.name || profile.id;
  const types = (profile.convergenceTypes || []).map((t) => `- \`${t}\``).join('\n') || '_(none)_';
  const tmpls = (profile.starterTemplates || []).map((t) => `- \`docs/templates/${t}\``).join('\n') || '_(none)_';
  return `# ${name}

Custom build of the [Living Doc Compositor](https://github.com/triadflow/living-doc-compositor) — ${profile.description || ''}

## What's included

**Convergence types**
${types}

**Starter templates**
${tmpls}

## Run it

\`\`\`bash
# render a starter to HTML
node scripts/render-living-doc.mjs docs/templates/<your-starter>.json

# serve docs/ to browse the compositor + rendered docs
cd docs && python3 -m http.server 8111
\`\`\`

Open http://localhost:8111/living-doc-compositor.html to compose docs in the branded GUI.

## Customize further

- Add new convergence types by editing \`scripts/living-doc-registry.json\` directly.
- Swap the primary color by editing \`--accent\` in \`docs/living-doc-compositor.html\`.
- Re-open the builder with this kit preselected: visit the gallery and pick \`${profile.id}\`.

Bundle generated by \`build-kit.mjs\` from profile \`${profile.id}\`.
`;
}

async function copyRepoFile(relPath, outDir) {
  const src = path.join(repoRoot, relPath);
  const dest = path.join(outDir, relPath);
  await mkdir(path.dirname(dest), { recursive: true });
  await cp(src, dest);
}

export async function buildKit(profile, outDir, { registry, compositorHtml } = {}) {
  await mkdir(outDir, { recursive: true });
  await mkdir(path.join(outDir, 'scripts'), { recursive: true });
  await mkdir(path.join(outDir, 'docs', 'templates'), { recursive: true });

  // Load inputs if not provided
  registry ??= JSON.parse(await readFile(path.join(repoRoot, 'scripts/living-doc-registry.json'), 'utf8'));
  compositorHtml ??= await readFile(path.join(repoRoot, 'docs/living-doc-compositor.html'), 'utf8');

  // Filtered registry
  const filtered = filterRegistry(registry, profile.convergenceTypes ?? []);
  await writeFile(
    path.join(outDir, 'scripts/living-doc-registry.json'),
    JSON.stringify(filtered, null, 2) + '\n',
  );

  // Branded compositor
  const branded = brandCompositor(compositorHtml, profile.defaultBranding);
  await writeFile(path.join(outDir, 'docs/living-doc-compositor.html'), branded);

  // Renderer + helpers (copied verbatim from repo)
  for (const rel of [
    'scripts/render-living-doc.mjs',
    'scripts/living-doc-i18n.json',
    'scripts/sync-compositor-embeds.mjs',
    'scripts/meta-fingerprint.mjs',
  ]) {
    await copyRepoFile(rel, outDir);
  }

  // Starter templates
  for (const tmpl of profile.starterTemplates ?? []) {
    const src = path.join(repoRoot, 'docs', tmpl);
    const dest = path.join(outDir, 'docs/templates', tmpl);
    await cp(src, dest);
  }

  // README
  await writeFile(path.join(outDir, 'README.md'), renderReadme(profile));

  return {
    outDir,
    includedTypes: Object.keys(filtered.convergenceTypes).length,
    includedEntityTypes: Object.keys(filtered.entityTypes).length,
    includedStatusSets: Object.keys(filtered.statusSets).length,
    includedTemplates: (profile.starterTemplates ?? []).length,
  };
}

// CLI entry
if (import.meta.url === `file://${process.argv[1]}`) {
  const profilePath = process.argv[2];
  if (!profilePath) {
    console.error('Usage: build-kit.mjs <profile.json> [out-dir]');
    process.exit(1);
  }
  const profile = JSON.parse(await readFile(path.resolve(profilePath), 'utf8'));
  const outDir = path.resolve(process.argv[3] || path.join('dist', `kit-${profile.id}`));
  const result = await buildKit(profile, outDir);
  console.log(`✔ Built ${profile.name} → ${path.relative(process.cwd(), outDir)}`);
  console.log(`  types: ${result.includedTypes} · entities: ${result.includedEntityTypes} · statuses: ${result.includedStatusSets} · templates: ${result.includedTemplates}`);
}
