import { defineConvergenceType } from '../define.mjs';

export default defineConvergenceType({
  "id": "change-log",
  "name": "Change Log",
  "category": "governance",
  "kind": "surface",
  "description": "Card-level changes to the living doc between a declared source commit (typically the commit the paired dossier was published from) and the current state. Each entry names one card that was added, updated, or removed, with a short field-level summary and a link back to the commit.",
  "structuralContract": "One-column card grid. Each card is one change entry with commit (short SHA), date, target card reference, change-kind status, and a summary of fields that changed. Generated by scripts/living-doc-changelog.mjs from the git diff of the living-doc JSON, not hand-maintained.",
  "notFor": [
    "narrative version history (use a blog post)",
    "period-boundary snapshots (the period-notes section already does that)",
    "editorial decisions about methodology (use decision-record)"
  ],
  "promptGuidance": {
    "operatingThesis": "The change-log is the reader's ambient signal for what drifted since the paired dossier was frozen. Entries are generated — don't hand-write them. If the entry looks wrong, fix the diff script, not the data.",
    "keepDistinct": [
      "commit SHA and commit subject",
      "the target section and card the change applied to",
      "the kind of change (added, updated, removed)",
      "the field-level summary (not the full before/after values)",
      "the source citation that prompted the change, if available"
    ],
    "inspect": [
      "Run scripts/living-doc-changelog.mjs <doc> <from-ref> to regenerate before publishing.",
      "Verify the from-ref matches the dossier-source-commit meta on the paired dossier piece."
    ],
    "update": [
      "Regenerate the section whenever the living doc is committed to — not per-edit.",
      "Leave historical entries in place; do not re-write past entries retroactively."
    ],
    "avoid": [
      "Do not hand-edit change-log entries.",
      "Do not include trivial field changes (timestamps, re-rendered ordering).",
      "Do not include removed cards without preserving their last known state in the entry."
    ]
  },
  "icon": "<path opacity='.26' d='M4 4h16v16H4z'/><path d='M6 8h12v1.5H6zm0 4h9v1.5H6zm0 4h12v1.5H6z'/><circle cx='19' cy='8.75' r='2' fill='currentColor'/>",
  "iconColor": "#6366f1",
  "projection": "card-grid",
  "columns": 1,
  "sources": [
    {
      "key": "notes",
      "entityType": null,
      "label": null
    }
  ],
  "statusFields": [
    {
      "key": "changeKind",
      "statusSet": "change-kind"
    }
  ],
  "textFields": [
    {
      "key": "commit",
      "label": "Commit"
    },
    {
      "key": "date",
      "label": "Date"
    },
    {
      "key": "subject",
      "label": "Commit subject"
    },
    {
      "key": "cardRef",
      "label": "Card"
    },
    {
      "key": "sectionRef",
      "label": "Section"
    },
    {
      "key": "sourceCitation",
      "label": "Source"
    }
  ],
  "detailsFields": [
    {
      "key": "fieldChanges",
      "label": "Fields changed"
    }
  ],
  "domain": "governance",
  "entityShape": [
    "change-entry"
  ]
});
